url: "https://verhem.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "VerHem" # the name of your site, e.g. ACME Corp.
description: "A FEM solver for 18 components Ginzburg-Landau partial differential equations"
