menu:
- {name: 'Install-Compile', url: '/install'}
- {name: 'Docs', url: '/docs'}
- {name: 'Contributions', url: '/contributions'}

documentations:
- {topic: 'Installation Instructions'}
- {topic: 'Your first run'}
- {topic: 'Menu of VerHem'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/timohyva'}
- {icon: 'gitlab', link: 'https://gitlab.com/timohyva'}
- {icon: 'twitter', link: 'https://twitter.com/HpcOrg'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
